### ISSUE TITLE
Pusher design

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/pusher#3]

**Comment by pboothe** [comment]
https://docs.google.com/document/d/1tbPzK2PPNLcvL5XGgE9YVRj5c0-0zgeosIBvjyC1Egc/edit#

To be turned into DESIGN.md once it is finished.

**Comment by pboothe** [comment]
Doc is currently under review by @stephen-soltesz

**Comment by stephen-soltesz** [comment]
lgtm
