### ISSUE TITLE
Pusher doesn't prune empty directories

### ISSUE THREAD

**Issue by pboothe** [m-lab/pusher#55]
After pusher has uploaded all files in a directory, it does not empty the directory and/or remove the inotify listener attached to that directory.  When a data directory is "sufficiently old" we should consider automatically pruning the directory tree.

I suggest a month old.  So if the month is `2019/05` (May 2019) and we still have empty directories like `2019/03` or `2017/12`, then all empty directories earlier than (but not including) `2019/04` should be deleted with `rmdir`. We should use `rmdir` because that command fails if those directories are not truly empty.

**Comment by pboothe** [comment]
This is really low priority, because the new platform scrubs the local disk on every boot, so garbage will only accumulate if we never reboot our machines for many years, and if we never reboot our machines for many years, we are mismanaging them in many other ways.

**Comment by nkinkade** [comment]
This was resolved in PR https://github.com/m-lab/pusher/pull/99
